### ISSUE TITLE
This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days

### ISSUE THREAD

**Issue by szepeviktor** [composer-wordpress/.github#2]
Please see https://github.com/composer-wordpress/build/actions?query=workflow%3ACron

**Comment by LeoColomb** [comment]
@szepeviktor Good catch, thanks for raising!
Enabled again, will try to make sure it does not happen again...

**Comment by szepeviktor** [comment]
> for at least 60 days

maybe it is enough to commit once every month...
`cron: "3 2 1 * *"`
